### ISSUE TITLE
Final technical difficulties

### ISSUE THREAD

**Issue by zlwilson** [9khine/HelpKiosk#10]
From final testing and pre-piloting these are the last little bugs:

1. Camera step 2 throws the incomplete message even when complete
2. Message step 3 stays highlighted even when step 4 is highlighted
3. Phone step 2 stays highlighted even when step 3 is highlighted
4. According to the console some videos for the phone tasks don't exist
5. Update splash screen to more directly identify functions (e.g. live view, demo video)–maybe with arrows

**Comment by zlwilson** [comment]
1. Camera step 2 is fixed

**Comment by 9khine** [comment]
Fixed issue #4 (phone call video name updated)

**Comment by 9khine** [comment]
issue #3 fixed automatically after issue #4

**Comment by 9khine** [comment]
New issues:
6. Contact: cannot go to the last step (saving contact) after entering the contact information.
7. Message: cannot complete last step (similar to contact)
8. Clock: cannot complete last step (similar to above)

**Comment by zlwilson** [comment]
Fixed 2, 6 and 7

Leaves:
5. Update splash screen to more directly identify functions (e.g. live view, demo video)–maybe with arrows
8. Clock: cannot complete last step (similar to above)

**Comment by zlwilson** [comment]
Fixed 8.

**Comment by zlwilson** [comment]
5. has been fixed
