### ISSUE TITLE
Update LiveView Highlight

### ISSUE THREAD

**Issue by 9khine** [9khine/HelpKiosk#2]
- Need to run through LiveView activity events in ADB logcat 
- Update the event names accordingly for each instruction step
- Ensure the repeated codes are nicely grouped in a single method

**Comment by zlwilson** [comment]
I've updated this for app launches, now all the instruction sets should block at least the first instruction (the instruction to launch the correct app)

**Comment by zlwilson** [comment]
Also, I've updated the highlighting (the yellow box locations) for Messages, Phone and Gallery, so all the highlight locations are correct now

**Comment by zlwilson** [comment]
New issue/focus: I don't understand how you can decide if an instruction should block or not. It looks like it is just a boolean value in the Instruction data structure but changing that from "true" to "false" doesn't seem to have any effect. How do we create instructions that don't block at all and just allow the user to proceed to the next step?

**Comment by zlwilson** [comment]
This issue is closed.
